/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
<<<<<<< HEAD
 * Generated at: 2023-07-07 05:51:01 UTC
=======
 * Generated at: 2023-07-21 04:01:16 UTC
>>>>>>> 2584c0c985f792a78db57c7e936ac034698a1193
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class community_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1685681160891L));
    _jspx_dependants.put("jar:file:/D:/_spring_workspace/bewithme_team/bewithme/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/bewithme/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
<<<<<<< HEAD
=======
      out.write("\r\n");
>>>>>>> 2584c0c985f792a78db57c7e936ac034698a1193
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/community.css\">\r\n");
<<<<<<< HEAD
      out.write("    <link rel=\"stylesheet\" href=\"https://unpkg.com/swiper@6.4.5/swiper.scss\">\r\n");
      out.write("<title>community</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
=======
      out.write("<title>community</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
>>>>>>> 2584c0c985f792a78db57c7e936ac034698a1193
      out.write("\r\n");
      out.write("        <!-- 좌측/ 전체 동일한 메뉴바 부분 -->\r\n");
      out.write("        <div class=\"left\">\r\n");
      out.write("            <img src=\"/resources/img/logo.png\" class=\"logo\" alt=\"\">\r\n");
      out.write("            <div class=\"menu_bar\">\r\n");
<<<<<<< HEAD
      out.write("                <button><a href=\"/menu/home\"> 🏠<span> Home</span></a></button><br>\r\n");
      out.write("                <button><a href=\"/menu/subject\">📝<span> Subject</span></a></button><br>\r\n");
      out.write("                <button><a href=\"/menu/community\">📖<span class=\"not\"> Community</span></a></button><br>\r\n");
      out.write("                <button><a href=\"/menu/qna\">📁<span> Q&A</span></a></button><br>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sebu\">\r\n");
      out.write("                <button><a href=\"\">⚙ Setting</a></button><br>\r\n");
      out.write("                <button><a href=\"/member/logout\">🗑 Log out</a></button><br>\r\n");
=======
      out.write("                <button da><a href=\"\"> 🏠<span> Home</span></a></button><br>\r\n");
      out.write("                <button><a href=\"\">📝<span> Subject</span></a></button><br>\r\n");
      out.write("                <button><a href=\"/community/communitypage\">📖<span class=\"not\"> Community</span></a></button><br>\r\n");
      out.write("                <button><a href=\"\">📁<span> Q&A</span></a></button><br>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"sebu\">\r\n");
      out.write("                <button><a href=\"\">⚙ Setting</a></button><br>\r\n");
      out.write("                <button><a href=\"\">🗑 Log out</a></button><br>\r\n");
>>>>>>> 2584c0c985f792a78db57c7e936ac034698a1193
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 우측/ Community 부분 -->\r\n");
      out.write("        <div class=\"right\">\r\n");
      out.write("\r\n");
      out.write("            <!-- 고정/ 메뉴 선택 -->\r\n");
      out.write("            <div class=\"nav_bar\">\r\n");
<<<<<<< HEAD
      out.write("                <div class=\"nav\">\r\n");
      out.write("                    <button> 전체 </button>\r\n");
      out.write("                    <button> 개발 </button>\r\n");
      out.write("                    <button> 상담 </button>\r\n");
      out.write("                    <button> MY </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"#\" class=\"question\">\r\n");
      out.write("                    <button>💡 질문하기</button>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"nav_line\"></div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- 스크롤/ 게시판 리스트 -->\r\n");
      out.write("            <div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"recommend_coment\">\r\n");
=======
      out.write("                <div class=\"navBtns\">\r\n");
      out.write("                    <button value=\"전체\"  onclick=\"kindVal('전체');\"> 전체 </button>\r\n");
      out.write("                    <button value=\"개발\"  onclick=\"kindVal('개발');\"> 개발 </button>\r\n");
      out.write("                    <button value=\"상담\" onclick=\"kindVal('상담');\"> 상담 </button>\r\n");
      out.write("                    <button value=\"MY\" onclick=\"kindVal('MY');\"> MY </button>\r\n");
      out.write("                </div>\r\n");
      out.write("	            <a href=\"/community/insert\" class=\"question\">\r\n");
      out.write("	               <button>💡 질문하기</button>\r\n");
      out.write("	            </a>\r\n");
      out.write("           </div>\r\n");
      out.write("            <div class=\"nav_line\"></div>\r\n");
      out.write("   \r\n");
      out.write("            <!-- 스크롤/ 게시판 리스트 -->\r\n");
      out.write("            <div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"recommend_coment\" id=\"recommend_coment\">\r\n");
>>>>>>> 2584c0c985f792a78db57c7e936ac034698a1193
      out.write("\r\n");
      out.write("                    <span>오늘의 추천 질문</span>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"button_list\">\r\n");
<<<<<<< HEAD
=======
      out.write("                   		<!-- 추천질문 좌/우 이동 -->\r\n");
>>>>>>> 2584c0c985f792a78db57c7e936ac034698a1193
      out.write("                        <button class=\"button_left\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"23\" height=\"23\" fill=\"currentColor\" class=\"bi bi-arrow-left\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                <path fill-rule=\"evenodd\" d=\"M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z\"/>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button class=\"button_right\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"23\" height=\"23\" fill=\"currentColor\" class=\"bi bi-arrow-right\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                <path fill-rule=\"evenodd\" d=\"M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z\"/>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
<<<<<<< HEAD
      out.write("                <div class=\"recommend\">\r\n");
      out.write("                    <div class=\"recommend_post\">\r\n");
      out.write("                        <div>개발</div>\r\n");
      out.write("                        <p><a href=\"/comment.html\">1111spring에서 get과 post의 차이가 뭔디? 오 테이스 오오</a></p>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" fill=\"currentColor\" class=\"bi bi-chat\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                    <path d=\"M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z\"/>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    2 |\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"10\" fill=\"currentColor\" class=\"bi bi-suit-heart-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                        <path d=\"M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z\"/>\r\n");
      out.write("                                    </svg> 1\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>조회</span> \r\n");
      out.write("                                <span>37</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"recommend_post\">\r\n");
      out.write("                        <div>개발</div>\r\n");
      out.write("                        <p><a href=\"#\">2222spring에서 get과 post의 차이가 뭔디?</a></p>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" fill=\"currentColor\" class=\"bi bi-chat\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                    <path d=\"M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z\"/>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    2 |\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"10\" fill=\"currentColor\" class=\"bi bi-suit-heart-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                        <path d=\"M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z\"/>\r\n");
      out.write("                                    </svg> 1\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>조회</span> \r\n");
      out.write("                                <span>37</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"recommend_post\">\r\n");
      out.write("                        <div>개발</div>\r\n");
      out.write("                        <p><a href=\"#\">33333spring에서 get과 post의 차이가 뭔디?</a></p>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" fill=\"currentColor\" class=\"bi bi-chat\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                    <path d=\"M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z\"/>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    2 |\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"10\" fill=\"currentColor\" class=\"bi bi-suit-heart-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                        <path d=\"M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z\"/>\r\n");
      out.write("                                    </svg> 1\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>조회</span> \r\n");
      out.write("                                <span>37</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"recommend_post\">\r\n");
      out.write("                        <div>개발</div>\r\n");
      out.write("                        <p><a href=\"#\">444 spring에서 get과 post의 차이가 뭔디?</a></p>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" fill=\"currentColor\" class=\"bi bi-chat\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                    <path d=\"M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z\"/>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    2 |\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"10\" fill=\"currentColor\" class=\"bi bi-suit-heart-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                        <path d=\"M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z\"/>\r\n");
      out.write("                                    </svg> 1\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>조회</span> \r\n");
      out.write("                                <span>37</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"recommend_post\">\r\n");
      out.write("                        <div>개발</div>\r\n");
      out.write("                        <p><a href=\"#\">5555 spring에서 get과 post의 차이가 뭔디?</a></p>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" fill=\"currentColor\" class=\"bi bi-chat\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                    <path d=\"M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z\"/>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    2 |\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"10\" fill=\"currentColor\" class=\"bi bi-suit-heart-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                        <path d=\"M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z\"/>\r\n");
      out.write("                                    </svg> 1\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>조회</span> \r\n");
      out.write("                                <span>37</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"recommend_post\">\r\n");
      out.write("                        <div>개발</div>\r\n");
      out.write("                        <p><a href=\"#\">6666spring에서 get과 post의 차이가 뭔디?</a></p>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" fill=\"currentColor\" class=\"bi bi-chat\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                    <path d=\"M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z\"/>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    2 |\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"10\" fill=\"currentColor\" class=\"bi bi-suit-heart-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                        <path d=\"M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z\"/>\r\n");
      out.write("                                    </svg> 1\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>조회</span> \r\n");
      out.write("                                <span>37</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"recommend_post\">\r\n");
      out.write("                        <div>개발</div>\r\n");
      out.write("                        <p><a href=\"#\">7777spring에서 get과 post의 차이가 뭔디?</a></p>\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" fill=\"currentColor\" class=\"bi bi-chat\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                    <path d=\"M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z\"/>\r\n");
      out.write("                                    </svg>\r\n");
      out.write("                                    2 |\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"10\" fill=\"currentColor\" class=\"bi bi-suit-heart-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                        <path d=\"M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z\"/>\r\n");
      out.write("                                    </svg> 1\r\n");
      out.write("                                </span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <span>조회</span> \r\n");
      out.write("                                <span>37</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
=======
      out.write("                <div class=\"recommend\" id=\"recommend\">\r\n");
      out.write("                    <!-- 추천 게시판 출력 부분 -->\r\n");
>>>>>>> 2584c0c985f792a78db57c7e936ac034698a1193
      out.write("                </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("                <div class=\"sort_bar\">\r\n");
      out.write("                    <div class=\"sort\">\r\n");
      out.write("                        <button> 최신순 </button>\r\n");
      out.write("                        <button> 인기순 </button> \r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"search\">\r\n");
      out.write("                        <img src=\"/resources/img/q.png\">\r\n");
<<<<<<< HEAD
      out.write("                        <input type=\"text\" placeholder=\"키워드로 검색\">\r\n");
=======
      out.write("                        <input type=\"text\" name=\"keyword\"  placeholder=\"키워드로 검색\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ph.sh.keyword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
>>>>>>> 2584c0c985f792a78db57c7e936ac034698a1193
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"main_line\"></div>\r\n");
      out.write("\r\n");
<<<<<<< HEAD
      out.write("                <div class=\"board\">\r\n");
      out.write("                    <!-- 게시판 출력 부분 -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"content_left\">\r\n");
      out.write("                        <div class=\"title\">spring에서 get과 post의 차이가 뭔디?</div>\r\n");
      out.write("                        <div class=\"reaction\">\r\n");
      out.write("                                <div>23.06.29 |</div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" fill=\"currentColor\" class=\"bi bi-chat\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                    <path d=\"M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z\"/>\r\n");
      out.write("                                    </svg> 2 |\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"10\" fill=\"currentColor\" class=\"bi bi-suit-heart-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                        <path d=\"M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z\"/>\r\n");
      out.write("                                    </svg> 1\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"content\">spring공부를 하고 있는데 get과 post의 차이를 이해 못하겠어요. 도와주세요ㅜㅜ. \r\n");
      out.write("                            그리고 그 뿐만이 아닙니다, 저는 잠이 옵니다. 자고싶고 놀고싶고 골드에 가고싶습니다. 그리고 \r\n");
      out.write("                            엄청난 천재가되어 자격증 시험도 한번에 붙고싶습니다 음하하 그리고 이건 연습으로 쓴 글이기 떄문에 \r\n");
      out.write("                            어디서 짤리려나 잘려랴절려~\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"content_right\">\r\n");
      out.write("                        <img src=\"/resources/img/it.jpg\" alt=\"it사진\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"content_bottom\">\r\n");
      out.write("                        <span>잠이와요정은</span>\r\n");
      out.write("                        <button class=\"like_button\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-suit-heart\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                            <path d=\"m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z\"/>\r\n");
      out.write("                          </svg>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"main_line\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"content_left\">\r\n");
      out.write("                        <div class=\"title\">spring에서 get과 post의 차이가 뭔디?</div>\r\n");
      out.write("                        <div class=\"reaction\">\r\n");
      out.write("                                <div>23.06.29 |</div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" fill=\"currentColor\" class=\"bi bi-chat\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                    <path d=\"M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z\"/>\r\n");
      out.write("                                    </svg> 2 |\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"10\" fill=\"currentColor\" class=\"bi bi-suit-heart-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                        <path d=\"M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z\"/>\r\n");
      out.write("                                    </svg> 1\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"content\">spring공부를 하고 있는데 get과 post의 차이를 이해 못하겠어요. 도와주세요ㅜㅜ. \r\n");
      out.write("                            그리고 그 뿐만이 아닙니다, 저는 잠이 옵니다. 자고싶고 놀고싶고 골드에 가고싶습니다. 그리고 \r\n");
      out.write("                            엄청난 천재가되어 자격증 시험도 한번에 붙고싶습니다 음하하 그리고 이건 연습으로 쓴 글이기 떄문에 \r\n");
      out.write("                            어디서 짤리려나 잘려랴절려~\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"content_right\">\r\n");
      out.write("                        <img src=\"/resources/img/it.jpg\" alt=\"it사진\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"content_bottom\">\r\n");
      out.write("                        <span>잠이와요정은</span>\r\n");
      out.write("                        <button class=\"like_button\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-suit-heart\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                            <path d=\"m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z\"/>\r\n");
      out.write("                          </svg>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"main_line\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"content_left\">\r\n");
      out.write("                        <div class=\"title\">spring에서 get과 post의 차이가 뭔디?</div>\r\n");
      out.write("                        <div class=\"reaction\">\r\n");
      out.write("                                <div>23.06.29 |</div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"12\" fill=\"currentColor\" class=\"bi bi-chat\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                    <path d=\"M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z\"/>\r\n");
      out.write("                                    </svg> 2 |\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"12\" height=\"10\" fill=\"currentColor\" class=\"bi bi-suit-heart-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                        <path d=\"M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z\"/>\r\n");
      out.write("                                    </svg> 1\r\n");
      out.write("                                </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"content\">spring공부를 하고 있는데 get과 post의 차이를 이해 못하겠어요. 도와주세요ㅜㅜ. \r\n");
      out.write("                            그리고 그 뿐만이 아닙니다, 저는 잠이 옵니다. 자고싶고 놀고싶고 골드에 가고싶습니다. 그리고 \r\n");
      out.write("                            엄청난 천재가되어 자격증 시험도 한번에 붙고싶습니다 음하하 그리고 이건 연습으로 쓴 글이기 떄문에 \r\n");
      out.write("                            어디서 짤리려나 잘려랴절려~\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"content_right\">\r\n");
      out.write("                        <img src=\"/resources/img/it.jpg\" alt=\"it사진\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"content_bottom\">\r\n");
      out.write("                        <span>잠이와요정은</span>\r\n");
      out.write("                        <button class=\"like_button\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-suit-heart\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                            <path d=\"m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z\"/>\r\n");
      out.write("                          </svg>\r\n");
      out.write("                        </button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"main_line\"></div>\r\n");
      out.write("\r\n");
      out.write("                </div> \r\n");
      out.write("\r\n");
      out.write("                <!-- 페이징 번호가 들어올 자리 -->\r\n");
      out.write("                <div class=\"paging\" style=\"margin-left: 45%;\">\r\n");
      out.write("                    1 2 3 4 5 6 7 8 9 10 >\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div> \r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("               \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"/resources/js/community.js\"></script>\r\n");
=======
      out.write("                <div class=\"board\" id=\"board\">\r\n");
      out.write("                    <!-- 게시판 출력 부분 -->\r\n");
      out.write("        		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"../resources/js/community.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	const id = '");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("	getRecommendList(\"전체\");\r\n");
      out.write("	getCommunityList(0,\"전체\");\r\n");
      out.write("</script>\r\n");
>>>>>>> 2584c0c985f792a78db57c7e936ac034698a1193
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/community/community.jsp(98,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue("1111");
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
